In [58]:
import numpy as np

def readInput(input, numSteps):
    grid = []
    lines = input.split("\n")
    readGrid = False
    for line in lines:
        if line == "":
            readGrid = True
            continue
        if readGrid:
            grid.append(line)
        else:
            rule = line
    
    #Create new grid with enough buffer for all iterations so we don't need on the fly resizing
    #And enough buffer that we can ignore the first/last row/column
    
    shift = numSteps+1
    N = 2*shift+len(grid)
    M = 2*shift+len(grid[0])
    resizeGrid = np.zeros((N,M), dtype = np.uint8)
    for i in range(0,len(grid)):
        for j in range(0,len(grid[0])):
            resizeGrid[shift+i][shift+j]= 1 if grid[i][j] == "#" else 0
            
    ruleArr = [1 if r == "#" else 0 for r in rule]
    return resizeGrid, ruleArr

#Update grid B using A, and return the reverse order for swaping memory.
def updateImages(A,B,ruleArr):
    dim = A.shape
    #Update inside the buffer that we allowed for
    for i in range(1,dim[0]-1):
        for j in range(1,dim[1]-1):
            key = (A[i-1][j-1] << 8) | (A[i-1][j] << 7) | (A[i-1][j+1] << 6) | \
                    (A[i][j-1] << 5) | (A[i][j] << 4) | (A[i][j+1]) << 3  | \
                    (A[i+1][j-1] << 2) | (A[i+1][j] << 1) | (A[i+1][j+1])
            B[i][j] = ruleArr[key]
            
    #Outside edge should be updated uniformly along the boundary
    bdryUpdate = ruleArr[0] if A[0][0] == 0 else ruleArr[-1]
    for cnt in range(0, dim[1]):
        B[0][cnt] = bdryUpdate
        B[dim[0]-1][cnt] = bdryUpdate
        
    for cnt in range(0, dim[0]):
        B[cnt][0] = bdryUpdate
        B[cnt][dim[1]-1]=bdryUpdate
            
    return B,A


numSteps = 2
A, ruleArr = readInput(input, numSteps)
B = np.zeros(A.shape, dtype = np.uint8)
for i in range(0, numSteps):
    A,B = updateImages(A,B, ruleArr)
print(A)
print(sum(A.flatten()))


[[0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0]
 [0 0 1 0 0 1 0 1 0 0 0]
 [0 1 0 1 0 0 0 1 1 1 0]
 [0 1 0 0 0 1 1 0 1 0 0]
 [0 1 0 0 0 0 0 1 0 1 0]
 [0 0 1 0 1 1 1 1 1 0 0]
 [0 0 0 1 0 1 1 1 1 1 0]
 [0 0 0 0 1 1 0 1 1 0 0]
 [0 0 0 0 0 1 1 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0]]
35


In [59]:
numSteps = 50
A, ruleArr = readInput(input, numSteps)
B = np.zeros(A.shape, dtype = np.uint8)
for i in range(0, numSteps):
    print("Count i=",i)
    A,B = updateImages(A,B, ruleArr)
print(A)
print(sum(A.flatten()))

Count i= 0
Count i= 1
Count i= 2
Count i= 3
Count i= 4
Count i= 5
Count i= 6
Count i= 7
Count i= 8
Count i= 9
Count i= 10
Count i= 11
Count i= 12
Count i= 13
Count i= 14
Count i= 15
Count i= 16
Count i= 17
Count i= 18
Count i= 19
Count i= 20
Count i= 21
Count i= 22
Count i= 23
Count i= 24
Count i= 25
Count i= 26
Count i= 27
Count i= 28
Count i= 29
Count i= 30
Count i= 31
Count i= 32
Count i= 33
Count i= 34
Count i= 35
Count i= 36
Count i= 37
Count i= 38
Count i= 39
Count i= 40
Count i= 41
Count i= 42
Count i= 43
Count i= 44
Count i= 45
Count i= 46
Count i= 47
Count i= 48
Count i= 49
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
3351


In [55]:
input = """..#.#..#####.#.#.#.###.##.....###.##.#..###.####..#####..#....#..#..##..###..######.###...####..#..#####..##..#.#####...##.#.#..#.##..#.#......#.###.######.###.####...#.##.##..#..#..#####.....#.#....###..#.##......#.....#..#..#..##..#...##.######.####.####.#.#...#.......#..#.#.#...####.##.#......#..#...##.#.##..#...##.#.##..###.#......#.#.......#.#.#.####.###.##...#.....####.#..#..#.##.#....##..#.####....##...##..#...#......#.#.......#.......##..####..#...#.#.#...##..#.#..###..#####........#..####......#..#

#..#.
#....
##..#
..#..
..###"""